# Copyright (c) 2024-2026 Ziv Elovitch. All rights reserved.
# Licensed under the MIT License. See LICENSE file for details.

"""
Specctra SES Parser - Extract Routing Results
=============================================

Parses Specctra SES (Session) files generated by Freerouting.
Extracts routing information (wires, vias) for application back to PCB.

SES Format Overview:
- (session ...) top-level block
- (routes ...) contains routing results
  - (network_out ...) has net-specific routes
    - (wire ...) trace segments
    - (via ...) via definitions

GENERIC Design: Works for ANY circuit routed by Freerouting.

Author: Claude Code
Date: 2025-11-16
Version: 2.0.0

TC #51 FIX (2025-11-25): Intermittent Routing Failure Fix
=========================================================
ROOT CAUSES FIXED:
1. Parser state not cleared between parses (accumulated wires/vias)
2. Rigid regex patterns failing on edge cases
3. No fallback parsing for malformed wire definitions
4. No debug logging for parse failures

TC #76 FIX (2025-12-09): Via Dataclass Enhancement
==================================================
ROOT CAUSE: Via dataclass was missing fields required by manhattan_router.py
- Added drill_mm field with default value 0.4mm
- Added layers field with default value ["F.Cu", "B.Cu"]
This prevented TypeError crashes in the Manhattan Router fallback.
"""

from pathlib import Path
from typing import List, Dict, Any, Tuple, Optional
from dataclasses import dataclass, field
import re
import logging

# TC #51: Add proper logging for debugging intermittent failures
logger = logging.getLogger(__name__)


@dataclass
class Wire:
    """Routed wire segment. GENERIC for any net/layer."""
    net_name: str
    layer: str
    width_mm: float
    path_points: List[Tuple[float, float]] = field(default_factory=list)


@dataclass
class Via:
    """
    Routed via (layer transition). GENERIC for any position.

    TC #76 FIX (2025-12-09): Enhanced dataclass to support all router requirements.

    Fields:
        net_name: Name of the net this via belongs to
        x_mm: X position in millimeters
        y_mm: Y position in millimeters
        diameter_mm: Via pad diameter in millimeters
        drill_mm: Via drill hole diameter in millimeters (default: 0.4mm per JLCPCB)
        layers: List of copper layers this via connects (default: ["F.Cu", "B.Cu"])

    The drill_mm and layers fields are required by manhattan_router.py for creating
    vias during fallback routing. Without these fields, the router crashes with:
        TypeError: Via.__init__() got an unexpected keyword argument 'drill_mm'
    """
    net_name: str
    x_mm: float
    y_mm: float
    diameter_mm: float
    drill_mm: float = 0.4  # TC #76: Default drill size per JLCPCB minimum (0.3mm) + margin
    layers: List[str] = field(default_factory=lambda: ["F.Cu", "B.Cu"])  # TC #76: Default through-hole via


@dataclass
class RoutingData:
    """Complete routing results. GENERIC for any circuit."""
    wires: List[Wire] = field(default_factory=list)
    vias: List[Via] = field(default_factory=list)
    routed_nets: List[str] = field(default_factory=list)
    # TC #51: Add parse statistics for debugging
    parse_errors: List[str] = field(default_factory=list)
    raw_wire_count: int = 0  # Number of (wire statements found
    raw_via_count: int = 0   # Number of (via statements found


class SESParser:
    """
    Parse Specctra SES files from Freerouting.

    GENERIC: Works for ANY circuit complexity.

    TC #51 FIX (2025-11-25): STATELESS parser design
    - Parser state is CLEARED at the start of each parse() call
    - Prevents accumulated state from previous parses causing issues
    - Multiple regex patterns tried in sequence for robustness

    SES S-Expression Format:
    (session name
      (routes
        (network_out net_name
          (wire (path layer width x1 y1 x2 y2 ...))
          (via padstack x y)
        )
      )
    )
    """

    def __init__(self):
        """Initialize parser (stateless - state cleared on each parse)."""
        # TC #51 FIX: These are instance variables but CLEARED on each parse()
        self.wires: List[Wire] = []
        self.vias: List[Via] = []
        self.routed_nets: set = set()
        self.parse_errors: List[str] = []
        self.raw_wire_count: int = 0
        self.raw_via_count: int = 0

    def parse(self, ses_file: Path) -> RoutingData:
        """
        Parse SES file and extract routing data.

        TC #51 FIX (2025-11-25): STATELESS parser - state cleared at start
        This prevents accumulated state from previous parses causing issues.

        Args:
            ses_file: Path to .ses file from Freerouting

        Returns:
            RoutingData with wires and vias

        GENERIC: Works for ANY SES file from Freerouting.
        """
        # ═══════════════════════════════════════════════════════════════════════
        # TC #51 CRITICAL FIX: CLEAR ALL STATE at the start of each parse
        # ═══════════════════════════════════════════════════════════════════════
        # ROOT CAUSE: Parser instance was reused between circuits, accumulating
        # wires/vias from previous parses. This caused:
        #   - False "success" reports (showing wires from previous circuit)
        #   - Memory leaks on large batch runs
        #   - Intermittent failures when accumulated state interfered
        # ═══════════════════════════════════════════════════════════════════════
        self.wires = []
        self.vias = []
        self.routed_nets = set()
        self.parse_errors = []
        self.raw_wire_count = 0
        self.raw_via_count = 0

        print(f"[SESParser] DEBUG: Parsing SES file: {ses_file}")
        logger.debug(f"Parsing SES file: {ses_file}")

        if not ses_file.exists():
            error_msg = f"SES file does not exist: {ses_file}"
            print(f"[SESParser] ERROR: {error_msg}")
            logger.error(error_msg)
            self.parse_errors.append(error_msg)
            return RoutingData(parse_errors=[error_msg])

        try:
            content = ses_file.read_text()
        except Exception as e:
            error_msg = f"Failed to read SES file: {e}"
            print(f"[SESParser] ERROR: {error_msg}")
            logger.error(error_msg)
            self.parse_errors.append(error_msg)
            return RoutingData(parse_errors=[error_msg])

        print(f"[SESParser] DEBUG: SES file size: {len(content)} bytes")

        # TC #51: Count raw (wire and (via statements for diagnostics
        self.raw_wire_count = content.count('(wire')
        self.raw_via_count = content.count('(via')
        print(f"[SESParser] DEBUG: Raw counts: {self.raw_wire_count} (wire, {self.raw_via_count} (via statements")

        # Parse routing data with enhanced error handling
        self._parse_wires(content)
        self._parse_vias(content)

        # TC #51: Calculate parse success rate for diagnostics
        wire_success_rate = (len(self.wires) / self.raw_wire_count * 100) if self.raw_wire_count > 0 else 0
        via_success_rate = (len(self.vias) / self.raw_via_count * 100) if self.raw_via_count > 0 else 0

        print(f"[SESParser] DEBUG: Extracted {len(self.wires)} wires ({wire_success_rate:.1f}% of raw), "
              f"{len(self.vias)} vias ({via_success_rate:.1f}% of raw)")
        print(f"[SESParser] DEBUG: Routed {len(self.routed_nets)} nets: {sorted(self.routed_nets)[:10]}{'...' if len(self.routed_nets) > 10 else ''}")

        # TC #51: Warn if significant parse failures occurred
        if wire_success_rate < 90 and self.raw_wire_count > 0:
            warning = f"Low wire parse rate: {wire_success_rate:.1f}% ({len(self.wires)}/{self.raw_wire_count})"
            print(f"[SESParser] WARNING: {warning}")
            self.parse_errors.append(warning)

        if self.wires:
            sample_wire = self.wires[0]
            print(f"[SESParser] DEBUG: Sample wire: net={sample_wire.net_name}, layer={sample_wire.layer}, "
                  f"width={sample_wire.width_mm}mm, points={len(sample_wire.path_points)}")
        else:
            warning = "No wires extracted from SES file!"
            print(f"[SESParser] WARNING: {warning}")
            if self.raw_wire_count > 0:
                self.parse_errors.append(f"{warning} (but {self.raw_wire_count} raw wire statements found)")

        if self.vias:
            print(f"[SESParser] DEBUG: Sample via: net={self.vias[0].net_name}, "
                  f"pos=({self.vias[0].x_mm:.3f}, {self.vias[0].y_mm:.3f})mm")

        return RoutingData(
            wires=self.wires,
            vias=self.vias,
            routed_nets=list(self.routed_nets),
            parse_errors=self.parse_errors,
            raw_wire_count=self.raw_wire_count,
            raw_via_count=self.raw_via_count
        )

    def _parse_wires(self, content: str):
        """
        Extract wire (trace) segments from SES file.

        Wire format: (wire (path layer width x1 y1 x2 y2 x3 y3 ...))
        These appear within (net NAME ...) blocks inside (network_out ...).

        TC #51 FIX (2025-11-25): ROBUST wire parsing with multiple fallback patterns
        ═══════════════════════════════════════════════════════════════════════════
        ROOT CAUSE: Original regex was too rigid, failing on:
        - Extra whitespace between tokens
        - Quoted layer names (e.g., "F.Cu" vs F.Cu)
        - Different coordinate formats (scientific notation, negative numbers)
        - Multi-line wire definitions

        SOLUTION: Try multiple regex patterns in sequence, from strict to lenient.
        ═══════════════════════════════════════════════════════════════════════════

        FIXED FOR FREEROUTING 2.1.0: Handles nested (net NAME ...) structure.
        GENERIC: Works for ANY net, ANY layer, ANY number of segments.
        """
        # Step 1: Find the single (network_out ...) container block
        # TC #51: More lenient pattern with optional whitespace
        network_out_patterns = [
            r'\(network_out\s+(.*?)\s*(?=\(library_out|\Z)',  # Original pattern
            r'\(network_out(.*?)(?=\(library_out|\)$|\Z)',   # More lenient
        ]

        network_block = None
        for pattern in network_out_patterns:
            network_match = re.search(pattern, content, re.DOTALL)
            if network_match:
                network_block = network_match.group(1)
                break

        if not network_block:
            print("[SESParser] DEBUG: No network_out block found in SES file")
            logger.warning("No network_out block found in SES file")
            return  # No routing data in SES file

        # Step 2: Find all (net NAME ...) blocks INSIDE network_out
        # TC #51: Support both quoted and unquoted net names
        net_patterns = [
            r'\(net\s+"([^"]+)"(.*?)(?=\(net\s+|\Z)',     # Quoted net name
            r'\(net\s+(\S+)(.*?)(?=\(net\s+|\Z)',         # Unquoted net name
        ]

        # Use first pattern that finds matches
        net_matches = []
        for pattern in net_patterns:
            matches = list(re.finditer(pattern, network_block, re.DOTALL))
            if matches:
                net_matches = matches
                break

        if not net_matches:
            print("[SESParser] DEBUG: No net blocks found in network_out")
            logger.warning("No net blocks found in network_out")
            return

        # Step 3: Parse wires from each net block
        # TC #51: Multiple wire patterns from strict to lenient
        wire_patterns = [
            # Pattern 1: Standard format with quoted layer
            r'\(wire\s+\(path\s+"([^"]+)"\s+([\d.eE+-]+)((?:\s+[\d.eE+-]+)+)\s*\)',
            # Pattern 2: Standard format with unquoted layer
            r'\(wire\s+\(path\s+(\S+)\s+([\d.]+)((?:\s+[\d.\-]+)+)\s*\)',
            # Pattern 3: Lenient format with extra whitespace
            r'\(wire\s*\(\s*path\s+([^\s)]+)\s+([\d.eE+-]+)((?:\s+[\d.eE+-]+)+)\s*\)',
            # Pattern 4: Multi-line format
            r'\(wire\s*\(\s*path\s+([^\s)]+)\s+([\d.eE+-]+)\s*((?:[\d.eE+-]+\s*)+)\)',
        ]

        for net_match in net_matches:
            net_name = net_match.group(1).strip('"').strip()
            net_content = net_match.group(2)

            self.routed_nets.add(net_name)

            # Try each wire pattern until one works
            wires_found = False
            for wire_pattern in wire_patterns:
                for wire_match in re.finditer(wire_pattern, net_content, re.DOTALL):
                    wires_found = True
                    try:
                        layer = wire_match.group(1).strip('"')  # e.g., "B.Cu", "F.Cu"
                        width_raw = float(wire_match.group(2))  # SES units (micrometers)
                        width_mm = width_raw / 1000000  # Convert micrometers to mm
                        coords_str = wire_match.group(3)

                        # TC #51: Robust coordinate parsing with error handling
                        coords_raw = coords_str.split()
                        coords = []
                        for coord in coords_raw:
                            coord = coord.strip()
                            if coord:  # Skip empty strings
                                try:
                                    coords.append(float(coord) / 1000000)
                                except ValueError as e:
                                    logger.warning(f"Invalid coordinate '{coord}' in wire: {e}")
                                    continue

                        # Ensure we have even number of coordinates (x,y pairs)
                        if len(coords) % 2 != 0:
                            coords = coords[:-1]  # Drop last if odd

                        if len(coords) >= 4:  # Need at least 2 points (4 coords)
                            path_points = [(coords[i], coords[i+1]) for i in range(0, len(coords), 2)]

                            wire = Wire(
                                net_name=net_name,
                                layer=layer,
                                width_mm=width_mm,
                                path_points=path_points
                            )
                            self.wires.append(wire)
                        else:
                            logger.warning(f"Wire has too few coordinates ({len(coords)}), skipping")

                    except Exception as e:
                        logger.warning(f"Failed to parse wire in net {net_name}: {e}")
                        self.parse_errors.append(f"Wire parse error in {net_name}: {e}")

                if wires_found:
                    break  # Stop trying patterns if we found wires

    def _parse_vias(self, content: str):
        """
        Extract via definitions from SES file.

        Via format: (via padstack_name x y)
        These appear within (net NAME ...) blocks inside (network_out ...).

        TC #51 FIX (2025-11-25): ROBUST via parsing with multiple fallback patterns
        ═══════════════════════════════════════════════════════════════════════════
        ROOT CAUSE: Original regex was too rigid, similar issues as wire parsing.
        SOLUTION: Try multiple regex patterns in sequence.
        ═══════════════════════════════════════════════════════════════════════════

        FIXED FOR FREEROUTING 2.1.0: Handles nested (net NAME ...) structure.
        GENERIC: Works for ANY via type, ANY position.
        """
        # Step 1: Find the single (network_out ...) container block
        # TC #51: More lenient pattern with optional whitespace
        network_out_patterns = [
            r'\(network_out\s+(.*?)\s*(?=\(library_out|\Z)',  # Original pattern
            r'\(network_out(.*?)(?=\(library_out|\)$|\Z)',   # More lenient
        ]

        network_block = None
        for pattern in network_out_patterns:
            network_match = re.search(pattern, content, re.DOTALL)
            if network_match:
                network_block = network_match.group(1)
                break

        if not network_block:
            return  # No routing data in SES file

        # Step 2: Find all (net NAME ...) blocks INSIDE network_out
        # TC #51: Support both quoted and unquoted net names
        net_patterns = [
            r'\(net\s+"([^"]+)"(.*?)(?=\(net\s+|\Z)',     # Quoted net name
            r'\(net\s+(\S+)(.*?)(?=\(net\s+|\Z)',         # Unquoted net name
        ]

        # Use first pattern that finds matches
        net_matches = []
        for pattern in net_patterns:
            matches = list(re.finditer(pattern, network_block, re.DOTALL))
            if matches:
                net_matches = matches
                break

        # Step 3: Parse vias from each net block
        # TC #51: Multiple via patterns from strict to lenient
        via_patterns = [
            # Pattern 1: Standard format with quoted padstack
            r'\(via\s+"([^"]+)"\s+([\d.eE+-]+)\s+([\d.eE+-]+)',
            # Pattern 2: Standard format with unquoted padstack
            r'\(via\s+(\S+)\s+([\d.\-]+)\s+([\d.\-]+)',
            # Pattern 3: Lenient format with extra whitespace
            r'\(via\s*([^\s)]+)\s+([\d.eE+-]+)\s+([\d.eE+-]+)',
        ]

        for net_match in net_matches:
            net_name = net_match.group(1).strip('"').strip()
            net_content = net_match.group(2)

            # Try each via pattern until one works
            vias_found = False
            for via_pattern in via_patterns:
                for via_match in re.finditer(via_pattern, net_content, re.DOTALL):
                    vias_found = True
                    try:
                        padstack_name = via_match.group(1).strip('"')
                        x_raw = float(via_match.group(2))  # SES units
                        y_raw = float(via_match.group(3))  # SES units

                        # Convert to mm (SES format: 1000000 = 1mm)
                        x_mm = x_raw / 1000000
                        y_mm = y_raw / 1000000

                        # Extract diameter from padstack name (e.g., "0.800" → 0.8mm)
                        # Or from Via[0-1]_600:400_um format (600 = 0.6mm)
                        diameter_mm = 0.8  # Default fallback
                        try:
                            # Try standard Via[...] format: Via[0-1]_600:400_um
                            via_name_match = re.search(r'_(\d+):', padstack_name)
                            if via_name_match:
                                diameter_mm = int(via_name_match.group(1)) / 1000
                            else:
                                # Try to extract any number from padstack name
                                diameter_match = re.search(r'([\d.]+)', padstack_name)
                                if diameter_match:
                                    val = float(diameter_match.group(1))
                                    # If value > 10, assume micrometers
                                    diameter_mm = val / 1000 if val > 10 else val
                        except Exception:
                            pass  # Use default 0.8mm

                        via = Via(
                            net_name=net_name,
                            x_mm=x_mm,
                            y_mm=y_mm,
                            diameter_mm=diameter_mm
                        )
                        self.vias.append(via)

                    except Exception as e:
                        logger.warning(f"Failed to parse via in net {net_name}: {e}")
                        self.parse_errors.append(f"Via parse error in {net_name}: {e}")

                if vias_found:
                    break  # Stop trying patterns if we found vias


__all__ = ['SESParser', 'RoutingData', 'Wire', 'Via']
